### ISSUE TITLE
Add maven dependency into pom.xml instead of intellij.

### ISSUE THREAD

**Issue by CodeMySky** [ScreenBasedSimulator/ScreenBasedSimulator2#1]
Hi Tony,

I noticed that you have submitted a .iml file and that is intellij specific. I also noticed that there are some maven dependency specified in the file. I think if others want to run the project but without a intellij IDE it will fail right?

I think it is better to keep the project IDE unrelated.

Sean

**Comment by convexshiba** [comment]
All Maven dependencies are in pom.
iml file was only added to hub branch and will only be used internally in hub team.
We'll not merge this file into master.
