### ISSUE TITLE
Patient does not exist!

### ISSUE THREAD

**Issue by CodeMySky** [ScreenBasedSimulator/ScreenBasedSimulator2#4]
![28 pic_hd](https://cloud.githubusercontent.com/assets/1545856/11151547/b8516e3e-89fb-11e5-9c35-714ce645f31c.jpg)

**Comment by SarahQu** [comment]
Bug fixed. Patient with hash 'abcdefg' will always exist. However, the exception will still be triggered if sending patient with other hash.
