### ISSUE TITLE
Unity needs to have the ability to send drug name and dosage back to hub.

### ISSUE THREAD

**Issue by CodeMySky** [ScreenBasedSimulator/ScreenBasedSimulator2#9]
Including a input for dosage and a input for drug, and a submit button.
It needs to be done by Saturday

**Comment by convexshiba** [comment]
How many parameters do we need for drugs? Is it three? Name Concentration and Dose? Or do we only need two?

**Comment by CodeMySky** [comment]
In my opinion, we can fix the concentration and only let user input dosage and drug name

**Comment by convexshiba** [comment]
So the concentration will be fixed inside Biogears and only two params will be transferred?

**Comment by CodeMySky** [comment]
Can it be fixed in hub?

**Comment by convexshiba** [comment]
Yeah of course.
What should the concentration be fixed at?

**Comment by CodeMySky** [comment]
Let's start with 2mg/ml
